In [1]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv('datasets/splitting-the-field/baseball_positions.csv')
dataset.head()

            Name Team Position
0    Aaron Judge  NYY    OF/DH
1    Cal Raleigh  SEA     C/DH
2  Shohei Ohtani  LAD       DH
3      Juan Soto  NYM       OF
4   Tarik Skubal  DET       SP

In [9]:
positions = dataset['Position'].str.split('/')
positions = positions.explode()
positions = positions.value_counts().reset_index(name='Players')
positions = positions.sort_values('Players', ascending=False)
positions

  Position  Players
0       OF      294
1       SP      227
2       RP      222
3       DH      134
4       3B      127
5       2B      125
6       1B      114
7        C      106
8       SS       85

## How many players make up the third most popular position?

In [11]:
positions.loc[2, 'Players']

222